// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: deps.proto

package tests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhoneNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        int64                  `protobuf:"varint,1,opt,name=Region,proto3" json:"Region,omitempty"`
	No            int64                  `protobuf:"varint,2,opt,name=No,proto3" json:"No,omitempty"`
	Ext           string                 `protobuf:"bytes,3,opt,name=Ext,proto3" json:"Ext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneNumber) Reset() {
	*x = PhoneNumber{}
	mi := &file_deps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumber) ProtoMessage() {}

func (x *PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_deps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumber.ProtoReflect.Descriptor instead.
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return file_deps_proto_rawDescGZIP(), []int{0}
}

func (x *PhoneNumber) GetRegion() int64 {
	if x != nil {
		return x.Region
	}
	return 0
}

func (x *PhoneNumber) GetNo() int64 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *PhoneNumber) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

var File_deps_proto protoreflect.FileDescriptor

const file_deps_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"deps.proto\"G\n" +
	"\vPhoneNumber\x12\x16\n" +
	"\x06Region\x18\x01 \x01(\x03R\x06Region\x12\x0e\n" +
	"\x02No\x18\x02 \x01(\x03R\x02No\x12\x10\n" +
	"\x03Ext\x18\x03 \x01(\tR\x03ExtB%Z#github.com/dashengyeah/xlscfg/testsb\x06proto3"

var (
	file_deps_proto_rawDescOnce sync.Once
	file_deps_proto_rawDescData []byte
)

func file_deps_proto_rawDescGZIP() []byte {
	file_deps_proto_rawDescOnce.Do(func() {
		file_deps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deps_proto_rawDesc), len(file_deps_proto_rawDesc)))
	})
	return file_deps_proto_rawDescData
}

var file_deps_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_deps_proto_goTypes = []any{
	(*PhoneNumber)(nil), // 0: PhoneNumber
}
var file_deps_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deps_proto_init() }
func file_deps_proto_init() {
	if File_deps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deps_proto_rawDesc), len(file_deps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deps_proto_goTypes,
		DependencyIndexes: file_deps_proto_depIdxs,
		MessageInfos:      file_deps_proto_msgTypes,
	}.Build()
	File_deps_proto = out.File
	file_deps_proto_goTypes = nil
	file_deps_proto_depIdxs = nil
}
