// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: edge.proto

package tests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EdgeSheetRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=Label,proto3" json:"Label,omitempty"`
	Value         int64                  `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeSheetRow) Reset() {
	*x = EdgeSheetRow{}
	mi := &file_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeSheetRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeSheetRow) ProtoMessage() {}

func (x *EdgeSheetRow) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeSheetRow.ProtoReflect.Descriptor instead.
func (*EdgeSheetRow) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{0}
}

func (x *EdgeSheetRow) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *EdgeSheetRow) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *EdgeSheetRow) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type EdgeSheet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*EdgeSheetRow        `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeSheet) Reset() {
	*x = EdgeSheet{}
	mi := &file_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeSheet) ProtoMessage() {}

func (x *EdgeSheet) ProtoReflect() protoreflect.Message {
	mi := &file_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeSheet.ProtoReflect.Descriptor instead.
func (*EdgeSheet) Descriptor() ([]byte, []int) {
	return file_edge_proto_rawDescGZIP(), []int{1}
}

func (x *EdgeSheet) GetList() []*EdgeSheetRow {
	if x != nil {
		return x.List
	}
	return nil
}

var File_edge_proto protoreflect.FileDescriptor

const file_edge_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"edge.proto\"J\n" +
	"\fEdgeSheetRow\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x14\n" +
	"\x05Label\x18\x02 \x01(\tR\x05Label\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\x03R\x05Value\".\n" +
	"\tEdgeSheet\x12!\n" +
	"\x04List\x18\x01 \x03(\v2\r.EdgeSheetRowR\x04ListB%Z#github.com/dashengyeah/xlscfg/testsb\x06proto3"

var (
	file_edge_proto_rawDescOnce sync.Once
	file_edge_proto_rawDescData []byte
)

func file_edge_proto_rawDescGZIP() []byte {
	file_edge_proto_rawDescOnce.Do(func() {
		file_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)))
	})
	return file_edge_proto_rawDescData
}

var file_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_edge_proto_goTypes = []any{
	(*EdgeSheetRow)(nil), // 0: EdgeSheetRow
	(*EdgeSheet)(nil),    // 1: EdgeSheet
}
var file_edge_proto_depIdxs = []int32{
	0, // 0: EdgeSheet.List:type_name -> EdgeSheetRow
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_edge_proto_init() }
func file_edge_proto_init() {
	if File_edge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_edge_proto_rawDesc), len(file_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_edge_proto_goTypes,
		DependencyIndexes: file_edge_proto_depIdxs,
		MessageInfos:      file_edge_proto_msgTypes,
	}.Build()
	File_edge_proto = out.File
	file_edge_proto_goTypes = nil
	file_edge_proto_depIdxs = nil
}
