// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: example.proto

package tests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberSheetRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Phone         *PhoneNumber           `protobuf:"bytes,4,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Cities        []string               `protobuf:"bytes,5,rep,name=Cities,proto3" json:"Cities,omitempty"`
	PP            []*PhoneNumber         `protobuf:"bytes,6,rep,name=PP,proto3" json:"PP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberSheetRow) Reset() {
	*x = MemberSheetRow{}
	mi := &file_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberSheetRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberSheetRow) ProtoMessage() {}

func (x *MemberSheetRow) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberSheetRow.ProtoReflect.Descriptor instead.
func (*MemberSheetRow) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *MemberSheetRow) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *MemberSheetRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberSheetRow) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MemberSheetRow) GetPhone() *PhoneNumber {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *MemberSheetRow) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *MemberSheetRow) GetPP() []*PhoneNumber {
	if x != nil {
		return x.PP
	}
	return nil
}

type MemberSheet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*MemberSheetRow      `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberSheet) Reset() {
	*x = MemberSheet{}
	mi := &file_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberSheet) ProtoMessage() {}

func (x *MemberSheet) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberSheet.ProtoReflect.Descriptor instead.
func (*MemberSheet) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *MemberSheet) GetList() []*MemberSheetRow {
	if x != nil {
		return x.List
	}
	return nil
}

var File_example_proto protoreflect.FileDescriptor

const file_example_proto_rawDesc = "" +
	"\n" +
	"\rexample.proto\x1a\n" +
	"deps.proto\"\xa8\x01\n" +
	"\x0eMemberSheetRow\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x18\n" +
	"\aAddress\x18\x03 \x01(\tR\aAddress\x12\"\n" +
	"\x05Phone\x18\x04 \x01(\v2\f.PhoneNumberR\x05Phone\x12\x16\n" +
	"\x06Cities\x18\x05 \x03(\tR\x06Cities\x12\x1c\n" +
	"\x02PP\x18\x06 \x03(\v2\f.PhoneNumberR\x02PP\"2\n" +
	"\vMemberSheet\x12#\n" +
	"\x04List\x18\x01 \x03(\v2\x0f.MemberSheetRowR\x04ListB%Z#github.com/dashengyeah/xlscfg/testsb\x06proto3"

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_example_proto_goTypes = []any{
	(*MemberSheetRow)(nil), // 0: MemberSheetRow
	(*MemberSheet)(nil),    // 1: MemberSheet
	(*PhoneNumber)(nil),    // 2: PhoneNumber
}
var file_example_proto_depIdxs = []int32{
	2, // 0: MemberSheetRow.Phone:type_name -> PhoneNumber
	2, // 1: MemberSheetRow.PP:type_name -> PhoneNumber
	0, // 2: MemberSheet.List:type_name -> MemberSheetRow
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	file_deps_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
