// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: flat_fields.proto

package tests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlatSheetRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Active        int64                  `protobuf:"varint,4,opt,name=Active,proto3" json:"Active,omitempty"`
	Score         int64                  `protobuf:"varint,5,opt,name=Score,proto3" json:"Score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatSheetRow) Reset() {
	*x = FlatSheetRow{}
	mi := &file_flat_fields_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatSheetRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatSheetRow) ProtoMessage() {}

func (x *FlatSheetRow) ProtoReflect() protoreflect.Message {
	mi := &file_flat_fields_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatSheetRow.ProtoReflect.Descriptor instead.
func (*FlatSheetRow) Descriptor() ([]byte, []int) {
	return file_flat_fields_proto_rawDescGZIP(), []int{0}
}

func (x *FlatSheetRow) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *FlatSheetRow) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FlatSheetRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FlatSheetRow) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *FlatSheetRow) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type FlatSheet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FlatSheetRow        `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlatSheet) Reset() {
	*x = FlatSheet{}
	mi := &file_flat_fields_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlatSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlatSheet) ProtoMessage() {}

func (x *FlatSheet) ProtoReflect() protoreflect.Message {
	mi := &file_flat_fields_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlatSheet.ProtoReflect.Descriptor instead.
func (*FlatSheet) Descriptor() ([]byte, []int) {
	return file_flat_fields_proto_rawDescGZIP(), []int{1}
}

func (x *FlatSheet) GetList() []*FlatSheetRow {
	if x != nil {
		return x.List
	}
	return nil
}

var File_flat_fields_proto protoreflect.FileDescriptor

const file_flat_fields_proto_rawDesc = "" +
	"\n" +
	"\x11flat_fields.proto\"v\n" +
	"\fFlatSheetRow\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x14\n" +
	"\x05Count\x18\x02 \x01(\x03R\x05Count\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Active\x18\x04 \x01(\x03R\x06Active\x12\x14\n" +
	"\x05Score\x18\x05 \x01(\x03R\x05Score\".\n" +
	"\tFlatSheet\x12!\n" +
	"\x04List\x18\x01 \x03(\v2\r.FlatSheetRowR\x04ListB%Z#github.com/dashengyeah/xlscfg/testsb\x06proto3"

var (
	file_flat_fields_proto_rawDescOnce sync.Once
	file_flat_fields_proto_rawDescData []byte
)

func file_flat_fields_proto_rawDescGZIP() []byte {
	file_flat_fields_proto_rawDescOnce.Do(func() {
		file_flat_fields_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flat_fields_proto_rawDesc), len(file_flat_fields_proto_rawDesc)))
	})
	return file_flat_fields_proto_rawDescData
}

var file_flat_fields_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_flat_fields_proto_goTypes = []any{
	(*FlatSheetRow)(nil), // 0: FlatSheetRow
	(*FlatSheet)(nil),    // 1: FlatSheet
}
var file_flat_fields_proto_depIdxs = []int32{
	0, // 0: FlatSheet.List:type_name -> FlatSheetRow
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_flat_fields_proto_init() }
func file_flat_fields_proto_init() {
	if File_flat_fields_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flat_fields_proto_rawDesc), len(file_flat_fields_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flat_fields_proto_goTypes,
		DependencyIndexes: file_flat_fields_proto_depIdxs,
		MessageInfos:      file_flat_fields_proto_msgTypes,
	}.Build()
	File_flat_fields_proto = out.File
	file_flat_fields_proto_goTypes = nil
	file_flat_fields_proto_depIdxs = nil
}
