// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: multi.proto

package tests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeroSheetRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Level         int64                  `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroSheetRow) Reset() {
	*x = HeroSheetRow{}
	mi := &file_multi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroSheetRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroSheetRow) ProtoMessage() {}

func (x *HeroSheetRow) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroSheetRow.ProtoReflect.Descriptor instead.
func (*HeroSheetRow) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{0}
}

func (x *HeroSheetRow) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *HeroSheetRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeroSheetRow) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type HeroSheet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*HeroSheetRow        `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroSheet) Reset() {
	*x = HeroSheet{}
	mi := &file_multi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroSheet) ProtoMessage() {}

func (x *HeroSheet) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroSheet.ProtoReflect.Descriptor instead.
func (*HeroSheet) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{1}
}

func (x *HeroSheet) GetList() []*HeroSheetRow {
	if x != nil {
		return x.List
	}
	return nil
}

type ItemSheetRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=Price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemSheetRow) Reset() {
	*x = ItemSheetRow{}
	mi := &file_multi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSheetRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSheetRow) ProtoMessage() {}

func (x *ItemSheetRow) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSheetRow.ProtoReflect.Descriptor instead.
func (*ItemSheetRow) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{2}
}

func (x *ItemSheetRow) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ItemSheetRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemSheetRow) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ItemSheet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ItemSheetRow        `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemSheet) Reset() {
	*x = ItemSheet{}
	mi := &file_multi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemSheet) ProtoMessage() {}

func (x *ItemSheet) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemSheet.ProtoReflect.Descriptor instead.
func (*ItemSheet) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{3}
}

func (x *ItemSheet) GetList() []*ItemSheetRow {
	if x != nil {
		return x.List
	}
	return nil
}

var File_multi_proto protoreflect.FileDescriptor

const file_multi_proto_rawDesc = "" +
	"\n" +
	"\vmulti.proto\"H\n" +
	"\fHeroSheetRow\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Level\x18\x03 \x01(\x03R\x05Level\".\n" +
	"\tHeroSheet\x12!\n" +
	"\x04List\x18\x01 \x03(\v2\r.HeroSheetRowR\x04List\"H\n" +
	"\fItemSheetRow\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Price\x18\x03 \x01(\x03R\x05Price\".\n" +
	"\tItemSheet\x12!\n" +
	"\x04List\x18\x01 \x03(\v2\r.ItemSheetRowR\x04ListB%Z#github.com/dashengyeah/xlscfg/testsb\x06proto3"

var (
	file_multi_proto_rawDescOnce sync.Once
	file_multi_proto_rawDescData []byte
)

func file_multi_proto_rawDescGZIP() []byte {
	file_multi_proto_rawDescOnce.Do(func() {
		file_multi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multi_proto_rawDesc), len(file_multi_proto_rawDesc)))
	})
	return file_multi_proto_rawDescData
}

var file_multi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_multi_proto_goTypes = []any{
	(*HeroSheetRow)(nil), // 0: HeroSheetRow
	(*HeroSheet)(nil),    // 1: HeroSheet
	(*ItemSheetRow)(nil), // 2: ItemSheetRow
	(*ItemSheet)(nil),    // 3: ItemSheet
}
var file_multi_proto_depIdxs = []int32{
	0, // 0: HeroSheet.List:type_name -> HeroSheetRow
	2, // 1: ItemSheet.List:type_name -> ItemSheetRow
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_multi_proto_init() }
func file_multi_proto_init() {
	if File_multi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multi_proto_rawDesc), len(file_multi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multi_proto_goTypes,
		DependencyIndexes: file_multi_proto_depIdxs,
		MessageInfos:      file_multi_proto_msgTypes,
	}.Build()
	File_multi_proto = out.File
	file_multi_proto_goTypes = nil
	file_multi_proto_depIdxs = nil
}
