// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: nested.proto

package tests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=Street,proto3" json:"Street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=City,proto3" json:"City,omitempty"`
	Zip           string                 `protobuf:"bytes,3,opt,name=Zip,proto3" json:"Zip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_nested_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_nested_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type NestedSheetRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Home          *Address               `protobuf:"bytes,3,opt,name=Home,proto3" json:"Home,omitempty"`
	Info          *Contact               `protobuf:"bytes,4,opt,name=Info,proto3" json:"Info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedSheetRow) Reset() {
	*x = NestedSheetRow{}
	mi := &file_nested_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedSheetRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedSheetRow) ProtoMessage() {}

func (x *NestedSheetRow) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedSheetRow.ProtoReflect.Descriptor instead.
func (*NestedSheetRow) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{2}
}

func (x *NestedSheetRow) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *NestedSheetRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedSheetRow) GetHome() *Address {
	if x != nil {
		return x.Home
	}
	return nil
}

func (x *NestedSheetRow) GetInfo() *Contact {
	if x != nil {
		return x.Info
	}
	return nil
}

type NestedSheet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*NestedSheetRow      `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedSheet) Reset() {
	*x = NestedSheet{}
	mi := &file_nested_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedSheet) ProtoMessage() {}

func (x *NestedSheet) ProtoReflect() protoreflect.Message {
	mi := &file_nested_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedSheet.ProtoReflect.Descriptor instead.
func (*NestedSheet) Descriptor() ([]byte, []int) {
	return file_nested_proto_rawDescGZIP(), []int{3}
}

func (x *NestedSheet) GetList() []*NestedSheetRow {
	if x != nil {
		return x.List
	}
	return nil
}

var File_nested_proto protoreflect.FileDescriptor

const file_nested_proto_rawDesc = "" +
	"\n" +
	"\fnested.proto\"G\n" +
	"\aAddress\x12\x16\n" +
	"\x06Street\x18\x01 \x01(\tR\x06Street\x12\x12\n" +
	"\x04City\x18\x02 \x01(\tR\x04City\x12\x10\n" +
	"\x03Zip\x18\x03 \x01(\tR\x03Zip\"5\n" +
	"\aContact\x12\x14\n" +
	"\x05Email\x18\x01 \x01(\tR\x05Email\x12\x14\n" +
	"\x05Phone\x18\x02 \x01(\tR\x05Phone\"p\n" +
	"\x0eNestedSheetRow\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1c\n" +
	"\x04Home\x18\x03 \x01(\v2\b.AddressR\x04Home\x12\x1c\n" +
	"\x04Info\x18\x04 \x01(\v2\b.ContactR\x04Info\"2\n" +
	"\vNestedSheet\x12#\n" +
	"\x04List\x18\x01 \x03(\v2\x0f.NestedSheetRowR\x04ListB%Z#github.com/dashengyeah/xlscfg/testsb\x06proto3"

var (
	file_nested_proto_rawDescOnce sync.Once
	file_nested_proto_rawDescData []byte
)

func file_nested_proto_rawDescGZIP() []byte {
	file_nested_proto_rawDescOnce.Do(func() {
		file_nested_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nested_proto_rawDesc), len(file_nested_proto_rawDesc)))
	})
	return file_nested_proto_rawDescData
}

var file_nested_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nested_proto_goTypes = []any{
	(*Address)(nil),        // 0: Address
	(*Contact)(nil),        // 1: Contact
	(*NestedSheetRow)(nil), // 2: NestedSheetRow
	(*NestedSheet)(nil),    // 3: NestedSheet
}
var file_nested_proto_depIdxs = []int32{
	0, // 0: NestedSheetRow.Home:type_name -> Address
	1, // 1: NestedSheetRow.Info:type_name -> Contact
	2, // 2: NestedSheet.List:type_name -> NestedSheetRow
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nested_proto_init() }
func file_nested_proto_init() {
	if File_nested_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nested_proto_rawDesc), len(file_nested_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nested_proto_goTypes,
		DependencyIndexes: file_nested_proto_depIdxs,
		MessageInfos:      file_nested_proto_msgTypes,
	}.Build()
	File_nested_proto = out.File
	file_nested_proto_goTypes = nil
	file_nested_proto_depIdxs = nil
}
