// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: repeated.proto

package tests

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepeatedSheetRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Phones        []*PhoneNumber         `protobuf:"bytes,4,rep,name=Phones,proto3" json:"Phones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedSheetRow) Reset() {
	*x = RepeatedSheetRow{}
	mi := &file_repeated_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedSheetRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedSheetRow) ProtoMessage() {}

func (x *RepeatedSheetRow) ProtoReflect() protoreflect.Message {
	mi := &file_repeated_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedSheetRow.ProtoReflect.Descriptor instead.
func (*RepeatedSheetRow) Descriptor() ([]byte, []int) {
	return file_repeated_proto_rawDescGZIP(), []int{0}
}

func (x *RepeatedSheetRow) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RepeatedSheetRow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RepeatedSheetRow) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RepeatedSheetRow) GetPhones() []*PhoneNumber {
	if x != nil {
		return x.Phones
	}
	return nil
}

type RepeatedSheet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*RepeatedSheetRow    `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedSheet) Reset() {
	*x = RepeatedSheet{}
	mi := &file_repeated_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedSheet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedSheet) ProtoMessage() {}

func (x *RepeatedSheet) ProtoReflect() protoreflect.Message {
	mi := &file_repeated_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedSheet.ProtoReflect.Descriptor instead.
func (*RepeatedSheet) Descriptor() ([]byte, []int) {
	return file_repeated_proto_rawDescGZIP(), []int{1}
}

func (x *RepeatedSheet) GetList() []*RepeatedSheetRow {
	if x != nil {
		return x.List
	}
	return nil
}

var File_repeated_proto protoreflect.FileDescriptor

const file_repeated_proto_rawDesc = "" +
	"\n" +
	"\x0erepeated.proto\x1a\n" +
	"deps.proto\"p\n" +
	"\x10RepeatedSheetRow\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Tags\x18\x03 \x03(\tR\x04Tags\x12$\n" +
	"\x06Phones\x18\x04 \x03(\v2\f.PhoneNumberR\x06Phones\"6\n" +
	"\rRepeatedSheet\x12%\n" +
	"\x04List\x18\x01 \x03(\v2\x11.RepeatedSheetRowR\x04ListB%Z#github.com/dashengyeah/xlscfg/testsb\x06proto3"

var (
	file_repeated_proto_rawDescOnce sync.Once
	file_repeated_proto_rawDescData []byte
)

func file_repeated_proto_rawDescGZIP() []byte {
	file_repeated_proto_rawDescOnce.Do(func() {
		file_repeated_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repeated_proto_rawDesc), len(file_repeated_proto_rawDesc)))
	})
	return file_repeated_proto_rawDescData
}

var file_repeated_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_repeated_proto_goTypes = []any{
	(*RepeatedSheetRow)(nil), // 0: RepeatedSheetRow
	(*RepeatedSheet)(nil),    // 1: RepeatedSheet
	(*PhoneNumber)(nil),      // 2: PhoneNumber
}
var file_repeated_proto_depIdxs = []int32{
	2, // 0: RepeatedSheetRow.Phones:type_name -> PhoneNumber
	0, // 1: RepeatedSheet.List:type_name -> RepeatedSheetRow
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_repeated_proto_init() }
func file_repeated_proto_init() {
	if File_repeated_proto != nil {
		return
	}
	file_deps_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repeated_proto_rawDesc), len(file_repeated_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repeated_proto_goTypes,
		DependencyIndexes: file_repeated_proto_depIdxs,
		MessageInfos:      file_repeated_proto_msgTypes,
	}.Build()
	File_repeated_proto = out.File
	file_repeated_proto_goTypes = nil
	file_repeated_proto_depIdxs = nil
}
