// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.9.2
// source: constant.proto

package constant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConstantEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val string `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
}

func (x *ConstantEntry) Reset() {
	*x = ConstantEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstantEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstantEntry) ProtoMessage() {}

func (x *ConstantEntry) ProtoReflect() protoreflect.Message {
	mi := &file_constant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstantEntry.ProtoReflect.Descriptor instead.
func (*ConstantEntry) Descriptor() ([]byte, []int) {
	return file_constant_proto_rawDescGZIP(), []int{0}
}

func (x *ConstantEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConstantEntry) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

type ConstantList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*ConstantEntry `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
}

func (x *ConstantList) Reset() {
	*x = ConstantList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constant_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstantList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstantList) ProtoMessage() {}

func (x *ConstantList) ProtoReflect() protoreflect.Message {
	mi := &file_constant_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstantList.ProtoReflect.Descriptor instead.
func (*ConstantList) Descriptor() ([]byte, []int) {
	return file_constant_proto_rawDescGZIP(), []int{1}
}

func (x *ConstantList) GetData() []*ConstantEntry {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_constant_proto protoreflect.FileDescriptor

var file_constant_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x33, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x56, 0x61, 0x6c, 0x22, 0x32, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x73, 0x68, 0x65, 0x6e, 0x67, 0x79,
	0x65, 0x61, 0x68, 0x2f, 0x78, 0x6c, 0x73, 0x63, 0x66, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_constant_proto_rawDescOnce sync.Once
	file_constant_proto_rawDescData = file_constant_proto_rawDesc
)

func file_constant_proto_rawDescGZIP() []byte {
	file_constant_proto_rawDescOnce.Do(func() {
		file_constant_proto_rawDescData = protoimpl.X.CompressGZIP(file_constant_proto_rawDescData)
	})
	return file_constant_proto_rawDescData
}

var file_constant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_constant_proto_goTypes = []interface{}{
	(*ConstantEntry)(nil), // 0: ConstantEntry
	(*ConstantList)(nil),  // 1: ConstantList
}
var file_constant_proto_depIdxs = []int32{
	0, // 0: ConstantList.Data:type_name -> ConstantEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_constant_proto_init() }
func file_constant_proto_init() {
	if File_constant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_constant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstantEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constant_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstantList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_constant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constant_proto_goTypes,
		DependencyIndexes: file_constant_proto_depIdxs,
		MessageInfos:      file_constant_proto_msgTypes,
	}.Build()
	File_constant_proto = out.File
	file_constant_proto_rawDesc = nil
	file_constant_proto_goTypes = nil
	file_constant_proto_depIdxs = nil
}
